services:

  web:
    build: "frontend"
    networks:
      - faucet

  api:
    build: "backend"
    networks:
      - faucet

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - api
      - web
    networks:
      - faucet


networks:
  faucet:                    
    driver: bridge             
    ipam:                      
      config:                  
        - subnet: 192.168.42.0/24
