services:

  web:
    build: "server"
    networks:
      - faucet

networks:
  faucet:                    
    driver: bridge             
    ipam:                      
      config:                  
        - subnet: 192.168.42.0/24
